### ISSUE TITLE
Optimize author list SQL query

### ISSUE THREAD

**Issue by mdlincoln** [cmu-lib/dhweb_app#309]

**Comment by mdlincoln** [comment]
Trying to calculate the most recent affiliation & appellation in teh DB query with 


```python

newest_authorship = (
                Authorship.objects.filter(author=OuterRef("pk"))
                .order_by("-work__conference__year")
                .annotate(most_recent_affiliation=Max("affiliations"))
            )

            aq = all_authors.annotate(
                most_recent_first_name=Subquery(
                    newest_authorship.values("appellation__first_name")[:1]
                )
            )

            aq = all_authors.annotate(
                most_recent_affiliation=Subquery(
                    newest_authorship.values("most_recent_affiliation")[:1]
                ),
                most_recent_first_name=Subquery(
                    newest_authorship.values("appellation__first_name")[:1]
                ),
                most_recent_last_name=Subquery(
                    newest_authorship.values("appellation__last_name")[:1]
                ),
            )
```

Adding just one field works, but trying to add multiple fails with

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 252, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 80, in __iter__
    setattr(obj, attr_name, row[col_pos])
AttributeError: can't set attribute
```

**Comment by mdlincoln** [comment]
maybe this is where the `Prefetch()` command is supposed to work: https://stackoverflow.com/questions/60910345/django-annotate-multiple-fields-from-a-subquery

**Comment by mdlincoln** [comment]
Ah, turns out that repeating a new column name in the `annotate` call that was the same as the one called from the `values` call is what caused me grief. The query generates SQL just fine.
